name: Custom Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout the code

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
